### ISSUE TITLE
1er Parcial Algoritmos y Estructuras de Datos I 2022 2do Cuatrimestre

### ISSUE THREAD

**Issue by vainsito** [ExamenesViejos-FaMAF-Computacion/ExamenesViejos_AlgoritmosYEstructurasDeDatos1_FaMAF#1]
![WhatsApp Image 2022-09-27 at 13 45 34](https://user-images.githubusercontent.com/83676911/193325493-5a07f969-36c4-4aac-aab7-25b69a3b87d2.jpeg)

**Comment by IvanRenison** [comment]
Agregado
Muchas gracias
